server {
  listen 80;
  server_name _;

  location /socket.io/ {
    proxy_pass http://signaling-server:3000/socket.io/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
  }

  location /api/ {
    proxy_pass http://signaling-server:3000/;
    proxy_set_header Host $host;
  }

  location / {
    proxy_pass http://viewer-web:4173/;
    proxy_set_header Host $host;
  }
}
